apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn:  arn:aws:iam::228699574855:role/factory_node
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::228699574855:root
      username: root_user
      groups:
        - system:masters
    - userarn: arn:aws:iam::228699574855:user/Shyam
      username: shyam
      groups:
        - system:masters
    
